global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 2
   publish_frequency: 2
   static_map: false
   transform_tolerance: 0.5
   width: 30.0
   height: 30.0
   resolution: 0.1
   static_map: true
   rolling_window: false
